lib/pm_login_web/router.ex
defmodule PmLoginWeb.Router do
  use PmLoginWeb, :router

# COMMENTED ROUTES ARE NOT TO BE DELETED BUT JUST NOT USED AT THE TIME

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PmLoginWeb do
    pipe_through :browser

    #contributor route
    get "/logs", ProjectController, :logs
    get "/my_projects", ContributorController, :my_projects
    get "/my_tasks", ContributorController, :my_tasks


    #Project LiveView
    get "/boards/:id", ProjectController, :board
    get "/recaps", ProjectController, :recaps
    get "/all_tasks", ProjectController, :all_tasks
    #Monitoring context
    # resources "/statuses", StatusController
    get "tasks", ProjectController, :tasks
    get "attributed_tasks", ProjectController, :attributed_tasks
    resources "/projects", ProjectController
    get "/contributors", ProjectController, :contributors
    get "/contributors/:id", ProjectController, :show_contributor
    # resources "/priorities", PriorityController
    resources "/tasks", TaskController, except: [:index, :edit, :show, :new]
    # resources "/comments", CommentController

    #Login context
    resources "/rights", RightController
    resources "/users", UserController
    get "/admin_space", UserController, :admin_space

    #Services context
    resources "/companies", CompanyController
    get "/my_company", CompanyController, :my_company
    get "/services", CompanyController, :services
    # resources "/notifications", NotificationController
    resources "/editors", EditorController
    resources "/softwares", SoftwareController
    resources "/licenses", LicenseController
    resources "/assist_contracts", AssistContractController
    resources "/active_clients", ActiveClientController, except: [:edit, :show]
    resources "/clients_requests", ClientsRequestController
    get "/requests", ClientsRequestController, :requests
    get "/my_requests", ClientsRequestController, :my_requests
    get "/client_tasks", ClientsRequestController, :client_tasks
    get "/client_users", ClientsRequestController, :client_users

    #=== Sondage client ===#
    get "/requests/survey", ClientsRequestController, :survey

    # get ""
    get "/users/:id/edit_profile", UserController, :edit_profile
    get "/users/:id/edit_password", UserController, :edit_password
    get "/list_users", UserController, :list
    put "/profile/:id", UserController, :update_profile
    patch "/profile/:id", UserController, :update_profile
    put "/profile_pass/:id", UserController, :update_password
    patch "/profile_pass/:id", UserController, :update_password
    put "/user/:id", UserController, :archive
    patch "/user/:id", UserController, :archive
    put "/user/restore/:id", UserController, :restore
    patch "/user/restore/:id", UserController, :restore
    get "/", PageController, :index
    post "/auth", AuthController, :auth
    post "/test_auth", AuthController, :test_auth
    get "/signout", AuthController, :sign_out
  end

  # Other scopes may use custom stacks.
  # scope "/api", PmLoginWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PmLoginWeb.Telemetry
    end
  end
end

lib/pm_login_web/templates/page/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Vérifiez vos informations ci-dessous</p>
    </div>
  <% end %>

  <div class="row login__input">
    <span class="material-icons-round" style="font-size: 35px;color: gray;">account_box</span>
    <%= text_input f, :username, class: "un", id: "iu", align: "center", placeholder: "Identifiant/Adresse éléctronique" %>
  </div>
  <%= error_tag f, :req_uname_error %>

<div class="row login__input">
  <span class="material-icons-round" style="font-size: 35px;color: gray;">password</span>
  <%= password_input f, :password, class: "pass", align: "center", placeholder: "Mot de passe" %>
</div>
  <%= error_tag f, :req_pass_error %>

  <%= submit "Se connecter", class: "submit", align: "center" %>
<% end %>

<!-- <div id="login" class="container">
  <p id="title" align="center">MGBI/ MONITORING</p>
   <p class="sign" align="center">Connexion</p>
   <form action="/auth" method="post" class="form1">
     <input class="un" type="text" name="username" align="center" placeholder="Utilisateur">
     <input class="pass" type="password" name="password" align="center" placeholder="Mot de passe">
     <input type="hidden" name="_csrf_token" value="<%= Plug.CSRFProtection.get_csrf_token() %>">
     <button class="submit" align="center">Se connecter</button>
   </form>
   <a id="signup" href="<%= Routes.user_path(@conn, :new) %>">Inscription</a>
   </div> -->

lib/pm_login_web/templates/page/index.html.eex
<div id="login" class="container">
  <p id="title" align="center">MGBI/ MONITORING</p>
   <p class="sign" align="center">Connexion</p>

   <%= render "form.html", Map.put(assigns, :action, Routes.auth_path(@conn, :auth)) %>

   </div>