lib/pm_login_web/router.ex
defmodule PmLoginWeb.Router do
  use PmLoginWeb, :router

# COMMENTED ROUTES ARE NOT TO BE DELETED BUT JUST NOT USED AT THE TIME

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PmLoginWeb do
    pipe_through :browser

    #contributor route
    get "/logs", ProjectController, :logs
    get "/my_projects", ContributorController, :my_projects
    get "/my_tasks", ContributorController, :my_tasks


    #Project LiveView
    get "/boards/:id", ProjectController, :board
    get "/recaps", ProjectController, :recaps
    get "/all_tasks", ProjectController, :all_tasks
    #Monitoring context
    # resources "/statuses", StatusController
    get "tasks", ProjectController, :tasks
    get "attributed_tasks", ProjectController, :attributed_tasks
    resources "/projects", ProjectController
    get "/contributors", ProjectController, :contributors
    get "/contributors/:id", ProjectController, :show_contributor
    # resources "/priorities", PriorityController
    resources "/tasks", TaskController, except: [:index, :edit, :show, :new]
    # resources "/comments", CommentController

    #Login context
    resources "/rights", RightController
    resources "/users", UserController
    get "/admin_space", UserController, :admin_space

    #Services context
    resources "/companies", CompanyController
    get "/my_company", CompanyController, :my_company
    get "/services", CompanyController, :services
    # resources "/notifications", NotificationController
    resources "/editors", EditorController
    resources "/softwares", SoftwareController
    resources "/licenses", LicenseController
    resources "/assist_contracts", AssistContractController
    resources "/active_clients", ActiveClientController, except: [:edit, :show]
    resources "/clients_requests", ClientsRequestController
    get "/requests", ClientsRequestController, :requests
    get "/my_requests", ClientsRequestController, :my_requests
    get "/client_tasks", ClientsRequestController, :client_tasks
    get "/client_users", ClientsRequestController, :client_users

    #=== Sondage client ===#
    get "/requests/survey", ClientsRequestController, :survey

    # get ""
    get "/users/:id/edit_profile", UserController, :edit_profile
    get "/users/:id/edit_password", UserController, :edit_password
    get "/list_users", UserController, :list
    put "/profile/:id", UserController, :update_profile
    patch "/profile/:id", UserController, :update_profile
    put "/profile_pass/:id", UserController, :update_password
    patch "/profile_pass/:id", UserController, :update_password
    put "/user/:id", UserController, :archive
    patch "/user/:id", UserController, :archive
    put "/user/restore/:id", UserController, :restore
    patch "/user/restore/:id", UserController, :restore
    get "/", PageController, :index
    post "/auth", AuthController, :auth
    post "/test_auth", AuthController, :test_auth
    get "/signout", AuthController, :sign_out
  end

  # Other scopes may use custom stacks.
  # scope "/api", PmLoginWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PmLoginWeb.Telemetry
    end
  end
end

lib/pm_login_web/views/layout_view.ex
defmodule PmLoginWeb.LayoutView do
  use PmLoginWeb, :view
end

lib/pm_login_web/templates/layout/active_client_layout_live.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>MGBI/ Monitoring</title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@socket, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@socket, "/assets/app.js")}></script>
  </head>
  <body class="body-bg">
    <script>0</script>
    <header class="site-header">

      <div class="wrapper site-header__wrapper">
        <%= link "Monitoring - Mgbi", to: Routes.user_path(@socket, :index), class: "brand" %>
        <nav class="nav">
          <a  class="menu-btn nav__toggle"><div class="menu-btn__burger"></div></a>
          <ul class="nav__wrapper">
            <li class="nav__item"><a href={Routes.company_path(@socket, :my_company)} class="nav__item__link"><span class="material-icons mat__ico">maps_home_work</span><p>Ma société</p></a></li>
            <li class="nav__item"><a href={Routes.clients_request_path(@socket, :my_requests)} class="nav__item__link"><span class="material-icons mat__ico">receipt_long</span><p>Mes requêtes</p></a></li>
            <li class="nav__item"><a href={Routes.user_path(@socket, :index)} class="nav__item__link"><span class="material-icons mat__ico">home</span><p>Accueil</p></a></li>
            <li class="nav__item old__notif">
              <div class="dropdown">
                <% unseens = PmLogin.Services.list_my_notifications(@curr_user_id)
                |> Enum.count(fn(x) -> !(x.seen) end) %>
                <a href="#" title="Notifications" phx-click="switch-notif"><span class="material-icons mat__ico header__ico">notifications</span><span class="notification-span" style={"background-color: #{ if unseens == 0 do "transparent" end } !important;"}><b class="notification-nb" style={"position: relative; left: #{ if unseens > 9 do "0px !important" end };"}><%=
                  if unseens < 10 do
                    unseens
                  else
                    "9+"
                  end
                  %></b></span></a>

                <div class="dropdown-notif basecontents__without__radius" style={"display: #{if @show_notif, do: "block", else: "none" };"}>
                  <%= if length(@notifs)!=0 do %>
                    <p id="spin_a" title="Charger notifications" class="x__close__copy" style="text-align: center;"><i id="myspin" class="bi bi-arrow-clockwise notif__load" phx-click="load-notifs" phx-hook="SpinTest"></i></p>
                  <% end %>
                  <%= for notif <- @notifs do %>
                    <div class="row notif-link basecontents__without__radius" style={"background-color: #{ if not notif.seen, do: "lightgray" } ;"}>
                      <div class="column column-10">
                        <img class="profile-pic-notif" src={Routes.static_path(@socket, "/#{PmLogin.Login.get_profile_picture(notif.sender_id) }") } width="20"/>
                      </div>
                      <div class="column" style="width: 150px;">
                        <b class="notif-text"><%= notif.content %></b>
                        <br/><br/>
                        <i class="notif-date">il y a <%= PmLogin.Services.time_ago notif %></i>
                      </div>
                    </div>
                  <% end %>
                  <%= if length(@notifs)==0 do %>
                    <p>Aucune notification</p>
                  <% end %>
                </div>
              </div>
            </li>

            <li class="nav__item">
              <div class="dropdown">
                <a href={ Routes.user_path(@socket, :show, @curr_user_id) } class="nav__item__link">
                <img class="profile-pic-header" src={Routes.static_path(@socket, "/#{PmLogin.Login.get_profile_picture(@curr_user_id) }")} width="50" style="position: relative;top: 5px;"/>
                <p><%= PmLogin.Login.get_user!(@curr_user_id).username %></p></a>
                <div class="dropdown-content">
                  <a href={ Routes.user_path(@socket, :show, @curr_user_id) } class="admin__links" style="display: flex;justify-content: space-between;">
                    <p>Mon profil</p><p><i class="bi bi-person my-profile-icons"></i></p>
                  </a>
                  <a href={ Routes.auth_path(@socket, :sign_out) } class="admin__links" style="display: flex;justify-content: space-between;">
                    <p style="color: red;">Se déconnecter</p><p style="color: red;"><i class="bi bi-box-arrow-right deconnexion__icon"></i></p>
                  </a>
                </div>
              </div>
            </li>


            </ul>
        </nav>
      </div>

      <div class="mobile__notif" style="display: inline-block;">
                <% unseens = PmLogin.Services.list_my_notifications(@curr_user_id)
                |> Enum.count(fn(x) -> !(x.seen) end) %>
                <a href="#" title="Notifications" phx-click="switch-notif"><i class="bi bi-bell-fill mobile__notif__ico"></i><span class="notification-span" style={"background-color: #{ if unseens == 0 do "transparent" end } !important;"}><b class="notification-nb-mobile" style={"position: relative; left: #{ if unseens > 9 do "0px !important" end };"}><%=
                  if unseens < 10 do
                    unseens
                  else
                    "9+"
                  end
                  %></b></span></a>

                  <div class="mobile-dropdown-notif basecontents__without__radius" style={"display: #{ if @show_notif, do: "block", else: "none" };"}>
                    <%= if length(@notifs)!=0 do %>
                    <p class="x__close__copy" title="Charger notifications" style="text-align: center;"><i id="myspin" class="bi bi-arrow-clockwise notif__load" phx-click="load-notifs"></i></p>
                    <% end %>
                    <%= for notif <- @notifs do %>
                      <div class="row notif-link basecontents__without__radius" style={"background-color: #{ if not notif.seen, do: "lightgray" } ;"}>
                        <div class="column column-10">
                          <img class="profile-pic-notif" src={Routes.static_path(@socket, '/#{PmLogin.Login.get_profile_picture(notif.sender_id) }')} width="20"/>
                        </div>
                        <div class="column" style="width: 150px;">
                          <b class="notif-text"><%= notif.content %></b>
                          <br/><br/>
                          <i class="notif-date">il y a <%= PmLogin.Services.time_ago notif %></i>
                        </div>
                      </div>
                    <% end %>
                    <%= if length(@notifs)==0 do %>
                      <p>Aucune notification</p>
                    <% end %>
                  </div>
              </div>





    </header>


    <main id="main" role="main" class="container" phx-hook="AnimateAlert">
      <p class="alert alert-info basecontents" role="alert"
        phx-click="lv:clear-flash" id="alert_anim"
        phx-value-key="info"><%= live_flash(@flash, :info) %><%= if not is_nil(live_flash(@flash, :info)) do %><i class="bi bi-x alert__cross"></i><% end %></p>

      <p class="alert alert-danger" role="alert"
        phx-click="lv:clear-flash"
        phx-value-key="error"><%= live_flash(@flash, :error) %></p>
      <%= @inner_content %>
      <br/>
      <br/>

      <!--
      <span>
        <a href="<%= Routes.auth_path(@socket, :sign_out) %>" class="btn btn-outline-danger btn-lg"><i class="bi bi-box-arrow-left"></i> Déconnexion</a>
      </span>
      -->

        </main>
  </body>
  <footer id="foot" class="container-fluid">
    <div id="footcont" class="container">
      <p><span id="copyright__icon" class="material-icons">copyright</span>copyright MGBI / Project monitoring</p>
    </div>

  </footer>
</html>

lib/pm_login_web/templates/layout/admin_layout.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>MGBI/ Monitoring</title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@socket, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@socket, "/assets/app.js")}></script>
  </head>
  <body class="body-bg">
    <script>0</script>

    <header class="site-header">

      <div class="wrapper site-header__wrapper">

        <img class="profile-pic-header" src={Routes.static_path(@socket, "/#{PmLogin.Login.get_profile_picture(Plug.Conn.get_session(@socket, :curr_user_id)) }")} width="50"/>
        <%= link "Monitoring - Mgbi", to: Routes.user_path(@socket, :index), class: "brand" %>
        <nav class="nav">
          <a  class="menu-btn nav__toggle"><div class="menu-btn__burger"></div></a>
          <ul class="nav__wrapper">

            <li class="nav__item">
              <div class="dropdown">
                <a href="#" class="dropbtn">▼<i class="bi bi-people-fill"></i> Espace administrateur</a>
                <div class="dropdown-content basecontents__without__radius">
                  <%= link "Projets", to: Routes.project_path(@socket, :index)%>
                  <%= link "Sociétés", to: Routes.company_path(@socket, :index) %>
                  <%= link "Utilisateurs", to: Routes.user_path(@socket, :list) %>
                  <%= link "Droits/Statuts", to: Routes.right_path(@socket, :index) %>
                  <%= link "Clients", to: Routes.active_client_path(@socket, :index) %>
                </div>
              </div>
            </li>

            <li class="nav__item"><a href={Routes.user_path(@socket, :index)}><i class="bi bi-house-fill"></i> Accueil</a></li>
            <li class="nav__item"><a href={ Routes.user_path(@socket, :show, Plug.Conn.get_session(@socket, :curr_user_id)) }><i class="bi bi-person-circle"></i> Profil</a></li>
          </ul>
        </nav>
      </div>


    </header>


    <main id="main" role="main" class="container">
      <p class="alert alert-info basecontents" role="alert"><%= get_flash(@socket, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@socket, :error) %></p>

      <%= @inner_content %>
      <br/>
      <br/>

      <span>
        <a href={Routes.auth_path(@socket, :sign_out)} class="btn btn-outline-danger btn-lg"><i class="bi bi-box-arrow-left"></i> Déconnexion</a>
      </span>
        </main>
  </body>
  <footer id="foot" class="container-fluid">
    <div id="footcont" class="container">
      <p><span id="copyright__icon" class="material-icons">copyright</span>copyright MGBI / Project monitoring</p>
    </div>

  </footer>
</html>

lib/pm_login_web/templates/layout/admin_layout_live.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>MGBI/ Monitoring</title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@socket, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@socket, "/assets/app.js")}></script>
  </head>
  <body class="body-bg-dark">
    <script>0</script>

    <header class="site-header">

      <div class="wrapper site-header__wrapper">
        <%= link "Monitoring - Mgbi", to: Routes.user_path(@socket, :index), class: "brand" %>
        <nav class="nav">
          <a class="menu-btn nav__toggle"><div class="menu-btn__burger"></div></a>
          <ul class="nav__wrapper">

            <li class="nav__item">
              <div class="dropdown">
                <a href={Routes.user_path(@socket, :index)} class="nav__item__link"><span class="material-icons mat__ico" style="display: inline;">admin_panel_settings</span> <p class="header_link_text">Espace administrateur</p></a>
                <div class="dropdown-content">
                  <a href={Routes.project_path(@socket, :logs)} class="admin__links">
                    <span class="material-icons mat__ico">table_chart</span>
                    Tableau de bord
                  </a>                  
                  <a href={Routes.project_path(@socket, :index)} class="admin__links">
                    <span class="material-icons mat__ico">insert_chart</span>
                    Projets
                  </a>
                  <a href={Routes.project_path(@socket, :all_tasks)} class="admin__links">
                    <span class="material-icons mat__ico">checklist_rtl</span>
                    Tâches
                  </a>
                  <a href={Routes.company_path(@socket, :index)} class="admin__links"> 
                    <span class="material-icons mat__ico">maps_home_work</span>
                    Sociétés 
                  </a>
                  <a href={Routes.user_path(@socket, :list)} class="admin__links"> 
                    <span class="material-icons mat__ico">supervisor_account</span>
                    Utilisateurs
                  </a>
                  <a href={Routes.right_path(@socket, :index)} class="admin__links">
                    <span class="material-icons mat__ico">shield</span>
                    Droits/Statuts
                  </a>
                  <a href={Routes.active_client_path(@socket, :index)} class="admin__links">
                    <span class="material-icons mat__ico">person</span>
                    Clients
                  </a>
                </div>
              </div>
            </li>

            <li class="nav__item"><a href={Routes.user_path(@socket, :index)} class="nav__item__link"><span class="material-icons mat__ico">home</span><p>Accueil</p></a></li>

            <li class="nav__item old__notif">
              <div class="dropdown">
                <% unseens = PmLogin.Services.list_my_notifications(@curr_user_id)
                |> Enum.count(fn(x) -> !(x.seen) end) %>
                <a href="#" title="Notifications" phx-click="switch-notif"><span class="material-icons mat__ico header__ico">notifications</span><span class="notification-span" style={"background-color: #{ if unseens == 0 do "transparent" end } !important;"}><b class="notification-nb" style={"position: relative; left: #{ if unseens > 9 do "0px !important" end };"}><%=
                  if unseens < 10 do
                    unseens
                  else
                    "9+"
                  end
                  %></b></span></a>

                  <div class="dropdown-notif basecontents__without__radius" style={"display: #{ if @show_notif, do: "block", else: "none" };"}>
                    <%= if length(@notifs)!=0 do %>
                    <p id="spin_a" title="Charger notifications" class="x__close__copy" style="text-align: center;"><i id="myspin" class="bi bi-arrow-clockwise notif__load" phx-click="load-notifs" phx-hook="SpinTest"></i></p>
                    <% end %>
                    <%= for notif <- @notifs do %>
                      <div class="row notif-link basecontents__without__radius" style={"background-color: #{ if not notif.seen, do: "lightgray" } ;"}>
                        <div class="column column-10">
                          <img class="profile-pic-notif" src={ Routes.static_path(@socket, "/#{PmLogin.Login.get_profile_picture(notif.sender_id) }") } width="20"/>
                        </div>
                        <div class="column" style="width: 150px;">
                          <b class="notif-text"><%= notif.content %></b>
                          <br/><br/>
                          <i class="notif-date">il y a <%= PmLogin.Services.time_ago notif %></i>
                        </div>
                      </div>
                    <% end %>
                    <%= if length(@notifs)==0 do %>
                      <p>Aucune notification</p>
                    <% end %>
                  </div>
              </div>
            </li>

            <li class="nav__item">
              <div class="dropdown">
                <a href={ Routes.user_path(@socket, :show, @curr_user_id) } class="nav__item__link">
                <img class="profile-pic-header" src={Routes.static_path(@socket, "/#{PmLogin.Login.get_profile_picture(@curr_user_id) }")} width="50" style="position: relative;top: 5px;"/>
                <p><%= PmLogin.Login.get_user!(@curr_user_id).username %></p></a>
                <div class="dropdown-content">
                  <a href={ Routes.user_path(@socket, :show, @curr_user_id) } class="admin__links" style="display: flex;justify-content: space-between;">
                    <p>Mon profil</p><p><i class="bi bi-person my-profile-icons"></i></p>
                  </a>
                  <a href={ Routes.auth_path(@socket, :sign_out) } class="admin__links" style="display: flex;justify-content: space-between;">
                    <p style="color: red;">Se déconnecter</p><p style="color: red;"><i class="bi bi-box-arrow-right deconnexion__icon"></i></p>
                  </a>
                </div>
              </div>
            </li>


          </ul>
        </nav>
      </div>

      <div class="mobile__notif" style="display: inline-block;">
                <% unseens = PmLogin.Services.list_my_notifications(@curr_user_id)
                |> Enum.count(fn(x) -> !(x.seen) end) %>
                <a href="#" title="Notifications" phx-click="switch-notif"><i class="bi bi-bell-fill mobile__notif__ico"></i><span class="notification-span" style={"background-color: #{ if unseens == 0 do "transparent" end } !important;"}><b class="notification-nb-mobile" style={"position: relative; left: #{ if unseens > 9 do "0px !important" end };"}><%=
                  if unseens < 10 do
                    unseens
                  else
                    "9+"
                  end
                  %></b></span></a>

                  <div class="mobile-dropdown-notif basecontents__without__radius" style={"display: #{ if @show_notif, do: "block", else: "none" };"}>
                    <%= if length(@notifs)!=0 do %>
                    <p class="x__close__copy" title="Charger notifications" style="text-align: center;"><i id="myspin" class="bi bi-arrow-clockwise notif__load" phx-click="load-notifs"></i></p>
                    <% end %>
                    <%= for notif <- @notifs do %>
                      <div class="row notif-link basecontents__without__radius" style={"background-color: #{ if not notif.seen, do: "lightgray" } ;"}>
                        <div class="column column-10">
                          <img class="profile-pic-notif" src={Routes.static_path(@socket, "/#{PmLogin.Login.get_profile_picture(notif.sender_id) }")} width="20"/>
                        </div>
                        <div class="column" style="width: 150px;">
                          <b class="notif-text"><%= notif.content %></b>
                          <br/><br/>
                          <i class="notif-date">il y a <%= PmLogin.Services.time_ago notif %></i>
                        </div>
                      </div>
                    <% end %>
                    <%= if length(@notifs)==0 do %>
                      <p>Aucune notification</p>
                    <% end %>
                  </div>
              </div>


    </header>


    <main id="main" role="main" class="container" phx-hook="AnimateAlert">
      <p class="alert alert-info basecontents" role="alert"
        phx-click="lv:clear-flash" id="alert_anim"
        phx-value-key="info"><%= live_flash(@flash, :info) %><%= if not is_nil(live_flash(@flash, :info)) do %><i class="bi bi-x alert__cross"></i><% end %></p>

      <p class="alert alert-danger" role="alert"
        phx-click="lv:clear-flash"
        phx-value-key="error"><%= live_flash(@flash, :error) %></p>
      <%= @inner_content %>
      <br/>
      <br/>
      <!--
      <span>
        <a href="<%= Routes.auth_path(@socket, :sign_out) %>" class="btn btn-outline-danger btn-lg"><i class="bi bi-box-arrow-left"></i> Déconnexion</a>
      </span>
      -->
    </main>
  </body>
  <footer id="foot" class="container-fluid">
    <div id="footcont" class="container">
      <p><span id="copyright__icon" class="material-icons">copyright</span>copyright MGBI / Project monitoring</p>
    </div>

  </footer>
</html>

lib/pm_login_web/templates/layout/app.html.eex
<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>MGBI/ Monitoring</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="site-header">
      <div class="wrapper site-header__wrapper">

        <img class="profile-pic-header" src="<%= Routes.static_path(@conn, "/#{PmLogin.Login.get_profile_picture(Plug.Conn.get_session(@conn, :curr_user_id)) }") %>" width="50"/>
        <%= link "Mgbi", to: Routes.user_path(@conn, :index), class: "brand" %>
        <nav class="nav">
          <input id="hamburger" type="image"  src="<%= Routes.static_path(@conn, "/images/hamburger.png") %>" class="nav__toggle">
          <ul class="nav__wrapper">
            <li class="nav__item"><%= link "Accueil", to: Routes.user_path(@conn, :index) %></li>
            <li class="nav__item"><%= link "Profil", to: Routes.user_path(@conn, :show, Plug.Conn.get_session(@conn, :curr_user_id))%></li>
          </ul>
        </nav>
      </div>
    </header>
    <main id="main" role="main" class="container">
      <p class="alert alert-info basecontents" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p> -->

      <%= @inner_content %>
      <!-- <br/>
      <br/>
      <span>
        <a href="<%= Routes.auth_path(@conn, :sign_out) %>" class="btn btn-outline-danger btn-lg"><i class="bi bi-box-arrow-left"></i> Déconnexion</a>
      </span>
        </main>
  </body>
  <footer id="foot" class="container-fluid">
    <div id="footcont" class="container">
        <p>copyright @Cleemzy / Project monitoring</p>
    </div>

  </footer>
</html> -->

lib/pm_login_web/templates/layout/contributor_layout.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>MGBI/ Monitoring</title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@socket, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@socket, "/assets/app.js")}></script>
  </head>
  <body class="body-bg">
    <header class="site-header">
      <script>0</script>

      <div class="wrapper site-header__wrapper">
        <%= link "Monitoring - Mgbi", to: Routes.user_path(@socket, :index), class: "brand" %>
        <nav class="nav">
          <a  class="menu-btn nav__toggle"><div class="menu-btn__burger"></div></a>
          <ul class="nav__wrapper">
            <li class="nav__item"><a href={ Routes.contributor_path(@socket, :my_projects) }><i class="bi bi-kanban-fill"></i> Mes projets</a></li>
            <li class="nav__item"><a href={ Routes.user_path(@socket, :index) }><i class="bi bi-house-fill"></i> Accueil</a></li>
            <li class="nav__item">
              <div class="dropdown">
                <a href={ Routes.user_path(@socket, :show, @curr_user_id) } class="nav__item__link">
                <img class="profile-pic-header" src={Routes.static_path(@socket, "/#{PmLogin.Login.get_profile_picture(@curr_user_id) }")} width="50" style="position: relative;top: 5px;"/>
                <p><%= PmLogin.Login.get_user!(@curr_user_id).username %></p></a>
                <div class="dropdown-content">
                  <a href={ Routes.user_path(@socket, :show, @curr_user_id) } class="admin__links" style="display: flex;justify-content: space-between;">
                    <p>Mon profil</p><p><i class="bi bi-person my-profile-icons"></i></p>
                  </a>
                  <a href={ Routes.auth_path(@socket, :sign_out) } class="admin__links" style="display: flex;justify-content: space-between;">
                    <p style="color: red;">Se déconnecter</p><p style="color: red;"><i class="bi bi-box-arrow-right deconnexion__icon"></i></p>
                  </a>
                </div>
              </div>
            </li>

    
          </ul>
        </nav>
      </div>


    </header>


    <main id="main" role="main" class="container">
      <p class="alert alert-info basecontents" role="alert"><%= get_flash(@socket, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@socket, :error) %></p>

      <%= @inner_content %>
      <br/>
      <br/>
        </main>
  </body>
  <footer id="foot" class="container-fluid">
    <div id="footcont" class="container">
      <p><span id="copyright__icon" class="material-icons">copyright</span>copyright MGBI / Project monitoring</p>
    </div>

  </footer>
</html>